# Generated by Django 4.1 on 2022-09-29 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_echange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('massage', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('createdAt', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='ContactMail_DPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('massage', models.CharField(max_length=250)),
                ('createdAt', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='Drugs_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('composition', models.CharField(max_length=250)),
                ('prix_unitaire', models.FloatField()),
                ('code', models.CharField(max_length=9)),
                ('inRuptuer', models.BooleanField(default=False)),
                ('dosage', models.IntegerField()),
                ('vitality', models.CharField(choices=[('non vital', '0'), ('vital', '1'), ('essential', '2')], default='vital', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='Whearhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('descrrption', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='Pharmacien_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('fix_phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsol.pharmacie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=80)),
                ('subHeader', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('is_Server', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grociste_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('fix_phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('whearhous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsol.whearhouse')),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='Doc_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('fix_phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
    ]
