# Generated by Django 4.1 on 2022-09-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('massage', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
    ]
