# Generated by Django 4.1 on 2022-09-29 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techsol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_instocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('composition', models.CharField(max_length=250)),
                ('prix_unitaire', models.FloatField()),
                ('code', models.CharField(max_length=9)),
                ('inRuptuer', models.BooleanField(default=False)),
                ('dosage', models.IntegerField()),
                ('quantity_instock', models.IntegerField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('Pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsol.pharmacie')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
    ]
