# Generated by Django 4.1 on 2022-09-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsol', '0002_contactmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmail',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
    ]
