# Generated by Django 4.1 on 2022-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsol', '0003_rename_news_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.AddField(
            model_name='new',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
    ]
