# Generated by Django 4.1 on 2022-09-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsol', '0003_product_image_alter_contactmail_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_created=True)),
                ('certifNAme', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('certif', models.ImageField(upload_to='')),
                ('certifCode', models.IntegerField()),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='DemandeCertif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(max_length=50)),
                ('gouvernorat', models.CharField(max_length=20)),
                ('Fonction', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
    ]
