# Generated by Django 4.1 on 2022-09-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsol', '0004_alter_new_options_new_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('massage', models.CharField(max_length=250)),
                ('product', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
                ('createdAt', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
    ]
