# Generated by Django 4.1 on 2022-09-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsol', '0005_contact_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs_list',
            name='rupture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
