# Generated by Django 4.1 on 2022-09-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsol', '0006_drugs_list_rupture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='image',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whearhouse',
            name='image',
            field=models.ImageField(default=74, upload_to=''),
            preserve_default=False,
        ),
    ]
